version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "servy-ts-backend"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-12vz3nbuw7js"
s3_prefix = "servy-ts-backend"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
parameter_overrides = "MyPar=\"hola\""
